---

  - name: Sync tater code
    git: 
      repo: git@github.com:ecohealthalliance/tater.git
      dest: "{{ tater_checkout_destination }}"
      accept_hostkey: yes
      version: "{{tater_branch}}"
      force: yes
      key_file: /home/tater/.ssh/id_rsa
    notify: restart tater
    register: tater

  - name: "Creating git revision.txt file"
    shell: 'git log -1 --format="%H : %ai" > revision.txt'
    args:
      creates: "{{ tater_checkout_destination }}/revision.txt"
      chdir: "{{ tater_checkout_destination }}"
    when: tater.changed

  - name: Copy tater logo to custom error web directory
    shell: "cp {{ tater_checkout_destination }}/public/images/tater-logo.png /var/www/deploying/"
    sudo: yes
    sudo_user: root

  - file: path="{{ tater_checkout_destination }}/build" state=absent
    when: tater.changed

  - file: path="{{ tater_checkout_destination }}/bundle" state=absent
    when: tater.changed
  
  - file: path=/home/tater owner=tater group=tater recurse=yes

  - name: Meteor build
    shell: meteor build build
    sudo: yes
    sudo_user: tater
    args:
      creates: "{{ tater_checkout_destination }}/build/tater.tar.gz"
      chdir: "{{ tater_checkout_destination }}"

  - name: Extract build tarball
    shell: "tar -zxf {{ tater_checkout_destination }}/build/tater.tar.gz"
    args:
      chdir: "{{ tater_checkout_destination }}"
    sudo: yes
    sudo_user: tater   

  - name: Install npm modules
    shell: "/home/tater/.nvm/{{ nodejs_version }}/bin/npm install"
    args:
      chdir: "{{ tater_checkout_destination }}/bundle/programs/server"
    sudo: yes
    sudo_user: tater

  - file: path="/usr/local/bin/mongod" state=absent

  - name: Symlink latest installed mongod binary
    shell: "ln -s $(find /home/ -name mongod | sort | tail -1) /usr/local/bin/mongod;"
    sudo: yes

  - name: Install supervisord config
    template: src=tater.conf.j2 dest=/etc/supervisor/conf.d/tater.conf
    sudo: yes
    sudo_user: root
    notify: restart supervisor

  - file: path="{{ tater_checkout_destination }}/.meteor/local/db" state=directory owner=tater group=tater

  - name: Start tater
    supervisorctl: name="tater" state=started
    sudo: yes
    sudo_user: root
